(load "fau.lisp")
(fau_init 'a)
(fau_init 'b)
(fau_init 'c)
(fau_init 'd)
(set_father 'a 'c)
(set_father 'b 'd)
(setf (get 'a 'ratio) 3.0)
(setf (get 'b 'ratio) 5.0)
(fau_union 'a 'b 4.0)
(eq (get 'c 'ratio) (/ 21.0 7.0))
